language: objective-c

before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
  - sudo easy_install cpp-coveralls

script:
  - xctool test -project SensoriadaExample.xcodeproj -scheme SensoriadaExample -sdk iphonesimulator8.1 -destination "platform=iOS Simulator,name=iPhone 6,OS=8.1"

after_success: 
  ./coveralls.rb --exclude-folder SensoriadaExample/Classes/GUI --exclude-folder SensoriadaExampleTests
